### ISSUE TITLE
Redundant code

### ISSUE THREAD

**Issue by 318097** [pesto-students/batch5-pacman#10]
In the game, there are 6 components: 
* Wall
* Food
* Ghost
* Energizer
* Pacman
* Free space

which have a common rendered output. 
I guess having 1 single 'Cell' component can be helpful.
Thoughts?

**Comment by shivangg** [comment]
The problems with having the `Cell` as the component:

The same Cell component will do 5 different things depending upon the props it is given. 

Not only this leads to the 5 if-else checks(_and 5 implementations_) all in the `Cell.jsx` but also breaks the Single Responsibility Principle recommended by React.

From react docs:

> a component should ideally only do one thing. If it ends up growing, it should be decomposed into smaller subcomponents.

**As far as the redundancy is concerned**:
All the 5 entities will have diverging functionalities in near future. Currently, they all render the a grid with different colors which gives illusion of redundancy. This will change in future.

**Comment by Shalinit3** [comment]
I think it's following that principle, it's just doing one thing i.e rendering a single cell. We are just rendering different type of cell on the basis of props and state.
And if the calculation of state becomes complicated in future we can always make an HOC for it. That's what they are for.

**Comment by 318097** [comment]
Hmm, Interesting.

**Comment by 318097** [comment]
You guys can put in a vote & accept whatever is right. I just presented my thoughts. If it doesn't follow React principles, then we can use the older approach.
