### ISSUE TITLE
Socket: Problem in transferring data

### ISSUE THREAD

**Issue by 318097** [pesto-students/batch5-pacman#109]
PR #107 includes the code to transfer the updates from client to server & back again.  
![Screenshot from 2019-03-29 11-31-08](https://user-images.githubusercontent.com/18000784/55212564-35fc5c00-5216-11e9-9ee0-02f94d0c61cb.png)
This problem occurs when the whole 'room' object is sent back.

It works fine when 'pacmanOne' & 'pacmanTwo' is sent. (In short, there is a problem when huge data is sent)

Please come to a conclusion about this problem.

**Comment by shivangg** [comment]
@318097  Can you give the exact steps to reproduce this issue.

**Comment by shivangg** [comment]
Check for circular references in the `room` object.
Try stringifying the whole `room` object before sending. `stringify` will fail and tell if `room` has some circular references.

Take a look [here](https://github.com/socketio/socket.io/issues/1665#issuecomment-215063116)

**Comment by Shalinit3** [comment]
@318097 the event for sending new game state from server to client was already there. Please go through the startGame method in game controller. It sends the current game state to all the clients in the room. You just have to update the game state in the calculateNextGameState method. All the other things like sending game info at regular intervals from server to client, starting the game after 3 seconds and leaving the room have been done in my PR.

**Comment by 318097** [comment]
@Shalinit3 Ok, will check.
