### ISSUE TITLE
Condition for Game Termination

### ISSUE THREAD

**Issue by shivangg** [pesto-students/batch5-pacman#126]
The game should terminate on:
1. All food is eaten.
2. Both Pacmans are eaten by the Ghosts.
3. ~No direction change from either Pacman in the last 200 seconds.~

Emit `game-over` event from the server.

@318097 @kaushikb11 @hassan23 @Shalinit3 Any Views?

**Comment by kaushikb11** [comment]
1. The logic is pretty simple to check if all the food is eaten or not by the gridState. The game should finish after this.
2. We have to add a condition that if one Pacman is eaten by the Ghost, the game shouldn't stop.
3. We can safely assume that if both the Pacman don't move, the Ghosts will eventually eat them.

**Comment by 318097** [comment]
Condition 3 (No direction change from either Pacman in the last 200 seconds) is not required I guess

**Comment by shivangg** [comment]
I wrote that in case no client is interested in playing the game. But, yes, this can be removed.

**Comment by shivangg** [comment]
Resolved in #145
