### ISSUE TITLE
Food turns red during the frightened mode.

### ISSUE THREAD

**Issue by kaushikb11** [pesto-students/batch5-pacman#142]
It's hard for the user to figure out when the Frightened mode ends. It would be cool if the food turns red while the fright mode is true.

**Comment by shivangg** [comment]
Isn't the color of the ghost tell whether it is frightened or not? Why extra visual cue of making the food red?
When the 4 ghosts become normal color from blue, it means the Frightened mode has ended.

**Comment by kaushikb11** [comment]
Because it looks cooler visually? Just purple ghosts looks boring.
