### ISSUE TITLE
Create modal for home page

### ISSUE THREAD

**Issue by Shalinit3** [pesto-students/batch5-pacman#28]
Create a modal that opens on the home screen. 
The body should have a message and two buttons:
1. One for Login
2. Play as guest

**Comment by shivangg** [comment]
@Shalinit3  Also put the mockup image relevant for this component.

**Comment by Shalinit3** [comment]
![20190315_001905](https://user-images.githubusercontent.com/26483075/54437841-8a560500-475b-11e9-8149-1b4fdbc24681.jpg)

**Comment by hassan23** [comment]
resolved by #73
