### ISSUE TITLE
Game stops updating after sometime

### ISSUE THREAD

**Issue by shivangg** [pesto-students/batch5-pacman#80]
As shown in the GIF, after some time the game stops updating. @kaushikb11 Do you know why this might be happening?

![pacmanStopsForNoReason](https://user-images.githubusercontent.com/10586637/54912670-1e239000-4f17-11e9-9986-453793228166.gif)

**Comment by shivangg** [comment]
@kaushikb11 I think it because the ghost in the top right is stuck. The only way left to go is backward, but the algorithm doesn't allow that because `totalX` will be getting to `0`. 

We can add a condition that if all 3 forward cells are walls, it can take the opposite direction.

**Comment by kaushikb11** [comment]
It's not a bug. It's doing what it's supposed to do. There's a problem with the Pacman board. We shouldn't change the ideal working logic of the entity for the board. Need to do changes to the Pacman board. Check out the Pacman boards that are used. @shivangg

**Comment by shivangg** [comment]
@kaushikb11  Yeah, I made it work by changing opening the wall in the board. The board should be changed.
But this condition fails silently depending on the board. In the future, if someone is designing the board, he might think of the whole game stopping as a bug.
So we can either `console.log('no possible direction for ghost to move')` in this case or 
> We can add a condition that if all 3 forward cells are walls, ghosts can take the opposite direction.

**Comment by shivangg** [comment]
Solved in #82 by changing the board design
